spring:
  application:
    name: promptforge-backend

  profiles:
    active: local

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui

management:

  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

logging:

  file:
    path: logs

  level:
    root: INFO
    com.rahulagarwal.promptforge: DEBUG
    org.springframework: INFO
    org.hibernate: WARN

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

rag:
  storage:
    provider: minio
    location: uploads
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: promptforge-documents